# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faa35586698885625d1c6814aa4fd7a72aeb4399f0e534d8768b29f8c5b548245d165d7e86e2566fb903f6b1ecb4396cf008afafc2fda8bb806c885303e932a5

test:
  secret_key_base: 8fc545d85022a46868bc464ce878427d0a870b4c681f75537f6f544aab5e84d7f83564ae6a330c834400b8e32c88b104dcee396dc50fe615a4d0736418814049

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
